### ISSUE TITLE
Galaxy error when running fastqc on compute nodes

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware-services#11]
Having problems running stuff that works on a master galaxy node, but problems on multiple nodes:
First problem...

```
Can't exec "java": No such file or directory at /opt/clusterware/var/lib/galaxy/share/shed-tool-deps/FastQC/0.11.4/iuc/package_fastqc_0_11_4/a8f485b2efd9/fastqc line 277.
Traceback (most recent call last):
  File "/opt/clusterware/var/lib/galaxy/share/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/fastqc/28d39af2dd06/fastqc/rgFastQC.py", line 162, in <module>
    fastqc_runner.run_fastqc()
  File "/opt/clusterware/var/lib/galaxy/share/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/fastqc/28d39af2dd06/fastqc/rgFastQC.py", line 136, in run_fastqc
    self.copy_output_file_to_dataset()
  File "/opt/clusterware/var/lib/galaxy/share/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/fastqc/28d39af2dd06/fastqc/rgFastQC.py", line 109, in copy_output_file_to_dataset
    with open(result_file[0], 'rb') as fsrc:
IndexError: list index out of range
```

Installed java manually, second problem...

```
Traceback (most recent call last):
  File "/opt/clusterware/opt/galaxy/galaxy/lib/galaxy/jobs/runners/__init__.py", line 92, in run_next
    job_id = arg.get_id_tag()
AttributeError: 'AsynchronousJobState' object has no attribute 'get_id_tag'
Tool execution generated the following error message:
Failed to find or download one or more job outputs from remote server.
```

**Comment by vlj91** [comment]
Tried this again with 1.3.0 release - 

```
Traceback (most recent call last):
  File "/opt/clusterware/opt/galaxy/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 254, in __prepare_job
    remote_job_config = client.setup(tool.id, tool.version)
  File "/opt/clusterware/opt/galaxy/galaxy/lib/pulsar/client/client.py", line 75, in setup
    return self.setup_handler.setup(**setup_args)
  File "/opt/clusterware/opt/galaxy/galaxy/lib/pulsar/client/setup_handler.py", line 65, in setup
    return self.client.remote_setup(**setup_args)
  File "/opt/clusterware/opt/galaxy/galaxy/lib/pulsar/client/decorators.py", line 13, in replacement
    response = func(*args, **kwargs)
  File "/opt/clusterware/opt/galaxy/galaxy/lib/pulsar/client/client.py", line 167, in remote_setup
    return self._raw_execute("setup", setup_args)
  File "/opt/clusterware/opt/galaxy/galaxy/lib/pulsar/client/client.py", line 215, in _raw_execute
    return self.job_manager_interface.execute(command, args, data, input_path, output_path)
  File "/opt/clusterware/opt/galaxy/galaxy/lib/pulsar/client/interface.py", line 96, in execute
    response = self.transport.execute(url, method=method, data=data, input_path=input_path, output_path=output_path)
  File "/opt/clusterware/opt/galaxy/galaxy/lib/pulsar/client/transport/standard.py", line 34, in execute
    response = self._url_open(request, data)
  File "/opt/clusterware/opt/galaxy/galaxy/lib/pulsar/client/transport/standard.py", line 20, in _url_open
    return urlopen(request, data)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
```
